# Контрольные задачи
Задача 1. «Треугольник с максимальным периметром»

Массив A состоит из целых положительных чисел - длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно составить треугольник с положительной площадью - функция возвращает 0.

Пример 1.1: Ввод: [2,1,2] Вывод: 5

Пример 1.2: Ввод: [1,2,1] Вывод: 0

Пример 1.3: Ввод: [3,2,3,4] Вывод: 10

Пример 1.4: Ввод: [3,6,2,3] Вывод: 8

In [3]:
def maxPerimeter(arr):

    maxi = 0
    n = len(arr)
    arr.sort(reverse = True)

    for i in range(0, n - 2):
        if arr[i] < (arr[i + 1] + arr[i + 2]):
            maxi = max(maxi, arr[i] + 
                       arr[i + 1] + arr[i + 2])
            break

    if(maxi == 0):
        return 0
    else:
        return str(maxi)

def Pr1(arr):
    
    a = maxPerimeter(arr)

    print(a)

In [4]:
def Program1():

    arr = [2, 1, 2]
    Pr1(arr)
    
    arr = [1, 2, 1]
    Pr1(arr)
    
    arr = [3, 2, 3, 4]
    Pr1(arr)
    
    arr = [3, 6, 2, 3]
    Pr1(arr)
    
    arr = [7, 2, 9, 14, 5, 3, 1, 1, 2, 6]
    Pr1(arr)
    
print("Zadacha 1")
Program1()

Zadacha 1
5
0
10
8
30


# Задача 2. «Максимальное число»

Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы вместе они образовали максимально возможное число. Замечание: Результат может быть очень большим числом, поэтому представьте его как string, а не integer.

Пример 2.1: Ввод: nums = [10,5] Вывод: ”510”

Пример 2.2: Ввод: nums = [39,3,43,5,9] Вывод: ”9543393”

Пример 2.3: Ввод: nums = [1] Вывод: ”1”

Пример 2.4: Ввод: nums = [10] Вывод: ”10”

In [5]:
def Sravnenie(a, b):

    ab = str(a) + str(b)
    ba = str(b) + str(a)

    return ((int(ba) > int(ab)) - (int(ba) < int(ab)))

      

def myCompare(mycmp):

    class K(object):

        def __init__(self, obj, *args):

            self.obj = obj

        def __lt__(self, other):

            return mycmp(self.obj, other.obj) < 0

        def __gt__(self, other):

            return mycmp(self.obj, other.obj) > 0

        def __eq__(self, other):

            return mycmp(self.obj, other.obj) == 0

        def __le__(self, other):

            return mycmp(self.obj, other.obj) <= 0

        def __ge__(self, other):

            return mycmp(self.obj, other.obj) >= 0

        def __ne__(self, other):

            return mycmp(self.obj, other.obj) != 0

    return K



def Pr2(a):

    sorted_array = sorted(a, key=myCompare(Sravnenie))
    number = "".join([str(i) for i in sorted_array])

    print(number)

In [6]:
def Program2():
    
    nums = [10,5]
    Pr2(nums)
    
    nums = [39,3,43,5,9]
    Pr2(nums)
    
    nums = [1]
    Pr2(nums)
    
    nums = [10]
    Pr2(nums)
    
print("Zadacha 2")
Program2()

Zadacha 2
510
9543393
1
10


# Задача 3. 
«Сортировка диагоналей в матрице»
Дана матрица mat размером m * n, значения целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу.

In [7]:
import numpy

def sort_matrix(mat):
    height = len(mat)
    width = len(mat[0])

    for x_start in range(1, width):
        line = []
        x = x_start
        for y in range(height - (0 if width - height - x >= 0 else abs(width - height - x)) ):
            line.append(mat[y][x])
            x += 1
        #print(line)
        line.sort()
        #print(line)

        x = x_start
        for y in range(height - (0 if width - height - x >= 0 else abs(width - height - x)) ):
            mat[y][x] = line[y]
            x += 1

    for y_start in range(0, height):
        line = []
        y = y_start
        for x in range(width - (0 if height - width - y >= 0 else abs(height - width - y)) ):
            line.append(mat[y][x])
            y += 1
        #print(line)
        line.sort()
        #print(line)

        y = y_start
        for x in range(width - (0 if height - width - y >= 0 else abs(height - width - y)) ):
            mat[y][x] = line[x]
            y += 1

In [8]:
matrix = numpy.random.randint(0, 10, size=(5,4))
print(matrix)

sort_matrix(matrix)
print(matrix)

[[1 9 4 5]
 [1 7 8 9]
 [0 0 4 4]
 [9 5 4 6]
 [6 7 5 4]]
[[1 4 4 5]
 [0 4 8 9]
 [0 1 6 9]
 [7 5 4 7]
 [6 9 5 4]]


# Задачи из файла "Задачи на дом 27 февраля.docx"
Задача 2. Правильный подмногоугольник

Задан правильный N-угольник. Требуется выбрать наименьшее количество его вершин, которые также образуют правильный многоугольник.

Входные данные содержат одно целое число N (3 ≤ N ≤ 1012).

Вывод

Выведите одно число — наименьшее количество вершин заданного многоугольника, которые образуют правильный многоугольник.

In [10]:
from math import *

print("Input N")

N = int(input())
t = 0

if (N % 3) == 0:
    print('3')
elif (N % 2) == 1:
    for i in range(2, floor(sqrt(N)) + 1, 1):
        if (N % i) == 0:
            print(i)
            break
elif ((N % 2) == 0) and ((N % 4) != 0):
    for i in range(3, floor(sqrt(N)), 2):
        if (N % i) == 0:
            t = i
            break
    if t == 0:
        print(N // 2)
    else:
        print(t)
elif ((N % 4) == 0):
    print('4')
else:
    for i in range(3, N + 1, 1):
        if (N % i) == 0:
            print(i)
            break

Input N
9
3


# Задача 1.

В Тридевятом Царстве уже много лет как установилась конституционная монархия. В парламент Тридевятого царства входят 26 партий, обозначаемых строчными буквами английского алфавита от «a» до «z». Заседание парламента в соответствии с регламентом проходит по следующей схеме:

● В начале заседания никаких законопроектов на повестке дня не стоит.

● Любая партия (в том числе и та, которая внесла текущий законопроект) в любой момент времени может внести на обсуждение новый законопроект.

● При вносе партией нового законопроекта обсуждение предыдущего приостанавливается и начинается обсуждение нового. После того, как парламентарии голосуют за новый законопроект, обсуждение законопроекта, прерванного им, продолжается.

● Дискуссия по любому законопроекту обязана завершиться голосованием по этому законопроекту.

● В конце заседания не должно остаться внесённых законопроектов, дискуссия по которым не завершена.

Вам дана запись о событиях на сессии парламента. Каждое событие является либо внесением нового законопроекта, либо голосованием за какой-то законопроект, причём в обоих случаях известен номер партии, этот законопроект предложившей. События даны в том порядке, в котором они происходили. Проверьте, может ли данная запись о событиях соответствовать

какому-либо заседанию, удовлетворяющему порядку проведения, описанному выше.

Входные данные

Первая строка входных данных содержит одно целое число K – количество строк в записи сессии (1 ≤ K ≤ 1000). Каждая строка соответствует одному из двух событий:

● Add x – партия x внесла на голосование законопроект.

● Vote x – прошло голосование за документ, внесённый партией x.

Здесь x – строчная буква английского алфавита от «a» до «z», задающая партию

In [18]:
print("Input K")

stack_store = []
t = 0

K = int(input())

for i in range(K):
    S = str(input())
    
    if (S.find("Add") != -1):
        stack_store.append(S[4])
        
    if (S.find("Vote") != -1):
        if S[5] != stack_store[-1]:
            t = t - 1
        elif S[5] == stack_store[-1]:
            t = t + 1
            stack_store.pop()
        elif stack_store == []:
            t = t - 1
        

if stack_store != []:
    t = t - 1
    
if (t == (K / 2)) or ((K == 1) and (S == "")):
    print("YES")
else:
    print("NO")

Input K
2
Add y
Vote y
YES


# ЗАДАЧА 1
Даны две строки: s1 и s2 с одинаковым размером, проверьте, может ли
некоторая перестановка строки s1 “победить” некоторую перестановку
строки s2 или наоборот.
Строка x может “победить” строку y (обе имеют размер n), если x[i]> = y
[i] (в алфавитном порядке) для всех i от 0 до n-1.

Примеры:
Input: s1 = "abc", s2 = "xya"
Output: true

Объяснение: «ayx» - это перестановка строки s2 = «xya»,
которая “побеждает” строку s1 = «abc».
Input: s1 = "abe", s2 = "acd"
Output: false

Объяснение: Все перестановки для s1 = "abe": "abe", "aeb",
"bae", "bea", "eab" и "eba", а все перестановки для s2 =
"acd": "acd", «adc», «cad», «cda», «dac» и «ca». Однако нет
никакой перестановки строки s1, которая может нарушить
некоторую перестановку строки s2 и наоборот.
s1.length == n
s2.length == n
1 <= n <= 10^5


In [19]:
from itertools import permutations


def can_win(s_attack, s_defend):
    for i in range(len(s_attack)):
        if s_attack[i] < s_defend[i]:
            return False
    return True


def all_combinations(s1_origin, s2_origin):
    arr_all_comb1 = [''.join(p) for p in permutations(s1_origin)]
    arr_all_comb2 = [''.join(p) for p in permutations(s2_origin)]
    for s1 in arr_all_comb1:
        for s2 in arr_all_comb2:
            if s1 != s2:
                if can_win(s1, s2) or can_win(s2, s1):
                    return True
    return False

In [21]:
print(all_combinations('abe', 'acd'))
print(all_combinations('abc', 'xya'))

False
True


# ЗАДАЧА 2
Дана строка s, вернуть самую длинную полиндромную подстроку в s.

Примеры:
Input: s = "babad"
Output: "bab"
Note: "aba" is also a valid answer.
Input: s = "cbbd"
Output: "bb"


In [22]:
def isPalindrome(s):
    return s == s[::-1]


def longest_palindrome(s):
    s_longest_pal = ''
    length = len(s)
    arr_all_substrings = [s[i: j] for i in range(len(s))
           for j in range(i + 1, len(s) + 1)]

    for s1 in arr_all_substrings:
        if isPalindrome(s1):
            if len(s1) > len(s_longest_pal):
                s_longest_pal = s1
    return s_longest_pal

In [28]:
s = 'babad'
print(longest_palindrome(s))
s = 'cbbd'
print(longest_palindrome(s))

bab
bb


# ЗАДАЧА 3
Вернуть количество отдельных непустых подстрок текста, которые могут
быть записаны как конкатенация некоторой строки с самой собой (т.е. она
может быть записана, как a + a, где a - некоторая строка).

Примеры:
Input: text = "abcabcabc"
Output: 3

Explanation: The 3 substrings are "abcabc", "bcabca"
and "cabcab".


In [26]:
from math import ceil


def concat(s):

    return s == s[:ceil(len(s) / 2)] + s[:ceil(len(s) / 2)]


def all_concat(s):
    dict_of_concat = dict()
    length = len(s)
    arr_all_substrings = [s[i: j] for i in range(length)
           for j in range(i + 1, length + 1)]

    for s1 in arr_all_substrings:
        if concat(s1):
            dict_of_concat.__setitem__(s1, 0)
    return len(dict_of_concat)

In [27]:
s = 'abcabcabc'
print(all_concat(s))

3
